pickaxes:
  common:
    starter: 100
    trash: 200
    beam: 300
    oven: 400
    suit: 500
    rock: 600
    drip: 700
    pump: 800
    drift: 900
  uncommon:
    chance: 1000
    hot: 1200
    seat: 1400
    bronze: 1600
    cloud: 1800
    hook: 2000
  rare:
    tasty: 2500
    deep: 3000
    fresh: 3500
    juicy: 4000
    stacked: 4500
  epic:
    thin: 5000
    beach: 5500
    club: 6000
    steel: 6500
    polished: 7000
    invisible: 7500
  legendary:
    glacier: 8000
    tiger: 9000
    moon: 10000
  mythic:
    thick: 25000
    lion: 30000
    bridge: 40000
    flag: 50000
  cosmic:
    martian:
      fortune: 60000
      model: 5
    OTW:
      fortune: 70000
      model: 3
    solar:
      fortune: 80000
      model: 4
    horror:
      fortune: 90000
      model: 2
    vortex:
      fortune: 100000
      model: 1

armor:
  phantom:
    display_name: "<dark_blue><bold><underlined>Phantom</underlined></bold></dark_blue>"
    color: "<dark_blue>"
    set_bonus:
      extra_pickaxe_xp: 100
      double_rebirth_chance: 20
      sell_bonus: 0.5
      increased_damage: "phantom"
    items:
      helmet:
        name: "<dark_blue><bold><underlined>Phantom Helmet</underlined></bold></dark_blue>"
        material: "PLAYER_HEAD"
        skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzQ2ODMwZGE1ZjgzYTNhYWVkODM4YTk5MTU2YWQ3ODFhNzg5Y2ZjZjEzZTI1YmVlZjdmNTRhODZlNGZhNCJ9fX0="
      chestplate:
        name: "<dark_blue><bold><underlined>Phantom Chestplate</underlined></bold></dark_blue>"
        material: "LEATHER_CHESTPLATE"
      leggings:
        name: "<dark_blue><bold><underlined>Phantom Leggings</underlined></bold></dark_blue>"
        material: "LEATHER_LEGGINGS"
      boots:
        name: "<dark_blue><bold><underlined>Phantom Boots</underlined></bold></dark_blue>"
        material: "LEATHER_BOOTS"

  shorse:
    display_name: "<gray><bold><underlined>Skeleton Horse</underlined></bold></gray>"
    color: "<gray>"
    set_bonus:
      extra_pickaxe_xp: 20
      double_rebirth_chance: 0
      sell_bonus: 0.1
      increased_damage: "skeleton_horse"
    items:
      helmet:
        name: "<gray><bold><underlined>Skeleton Horse Helmet</underlined></bold></gray>"
        material: "PLAYER_HEAD"
        skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDdlZmZjZTM1MTMyYzg2ZmY3MmJjYWU3N2RmYmIxZDIyNTg3ZTk0ZGYzY2JjMjU3MGVkMTdjZjg5NzNhIn19fQ=="
      chestplate:
        name: "<gray><bold><underlined>Skeleton Horse Chestplate</underlined></bold></gray>"
        material: "LEATHER_CHESTPLATE"
      leggings:
        name: "<gray><bold><underlined>Skeleton Horse Leggings</underlined></bold></gray>"
        material: "LEATHER_LEGGINGS"
      boots:
        name: "<gray><bold><underlined>Skeleton Horse Boots</underlined></bold></gray>"
        material: "LEATHER_BOOTS"

  zoglin:
    display_name: "<red><bold><underlined>Zoglin</underlined></bold></red>"
    color: "<red>"
    set_bonus:
      extra_pickaxe_xp: 40
      double_rebirth_chance: 0
      sell_bonus: 0.2
      increased_damage: "zoglin"
    items:
      helmet:
        name: "<red><bold><underlined>Zoglin Helmet</underlined></bold></red>"
        material: "PLAYER_HEAD"
        skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzE5YjdiNWU5ZmZkNGUyMmI4OTBhYjc3OGI0Nzk1YjY2MmZhZmYyYjQ5NzhiZjgxNTU3NGU0OGIwZTUyYjMwMSJ9fX0="
      chestplate:
        name: "<red><bold><underlined>Zoglin Chestplate</underlined></bold></red>"
        material: "LEATHER_CHESTPLATE"
      leggings:
        name: "<red><bold><underlined>Zoglin Leggings</underlined></bold></red>"
        material: "LEATHER_LEGGINGS"
      boots:
        name: "<red><bold><underlined>Zoglin Boots</underlined></bold></red>"
        material: "LEATHER_BOOTS"

  polarbear:
    display_name: "<white><bold><underlined>Polar Bear</underlined></bold></white>"
    color: "<white>"
    set_bonus:
      extra_pickaxe_xp: 60
      double_rebirth_chance: 0
      sell_bonus: 0.3
      increased_damage: "polar_bear"
    items:
      helmet:
        name: "<white><bold><underlined>Polar Bear Helmet</underlined></bold></white>"
        material: "PLAYER_HEAD"
        skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzhhMzAyYjUyNGZlOTM4OTJhOWJiMDcwN2U1NmI4NzQ2NzE4ZjIxNGE0OGM4ZDk1NmMzZmQ5NDY4YmYyMTdjNSJ9fX0="
      chestplate:
        name: "<white><bold><underlined>Polar Bear Chestplate</underlined></bold></white>"
        material: "LEATHER_CHESTPLATE"
      leggings:
        name: "<white><bold><underlined>Polar Bear Leggings</underlined></bold></white>"
        material: "LEATHER_LEGGINGS"
      boots:
        name: "<white><bold><underlined>Polar Bear Boots</underlined></bold></white>"
        material: "LEATHER_BOOTS"

  irongolem:
    display_name: "<gray><bold><underlined>Iron Golem</underlined></bold></gray>"
    color: "<gray>"
    set_bonus:
      extra_pickaxe_xp: 70
      double_rebirth_chance: 0
      sell_bonus: 0.4
      increased_damage: "iron_golem"
    items:
      helmet:
        name: "<gray><bold><underlined>Iron Golem Helmet</underlined></bold></gray>"
        material: "PLAYER_HEAD"
        skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmNlY2JhMzFmMjY5MTlkOTJhM2Q2NDIwY2QyZmE5MTEyZjhlMTA4YWMwNGUzZmM3MWRhNzMyOWNkMTBmZTVjYSJ9fX0="
      chestplate:
        name: "<gray><bold><underlined>Iron Golem Chestplate</underlined></bold></gray>"
        material: "LEATHER_CHESTPLATE"
      leggings:
        name: "<gray><bold><underlined>Iron Golem Leggings</underlined></bold></gray>"
        material: "LEATHER_LEGGINGS"
      boots:
        name: "<gray><bold><underlined>Iron Golem Boots</underlined></bold></gray>"
        material: "LEATHER_BOOTS"